In [24]:
import pandas as pd
import os
import numpy as np
from typing import Dict, Tuple, NamedTuple
from dotenv import load_dotenv
from pipeline.src.utils import load_yaml, load_parquet_from_gcs
from pipeline.src.transform.results_utils import wide_to_long_results
from pipeline.src.transform.utils import add_all_cumsum_columns
from sklearn.model_selection import train_test_split

In [25]:
# Load enviroment variables from .env
load_dotenv()

# Load the config file 
config = load_yaml(os.path.join('pipeline', 'config', 'config.yaml'))

In [26]:
# Load the dataframes
def load_dataframes(config):
    """
    Loads dataframes from GCS based on the provided configuration.

    Parameters:
        config (dict): A dictionary containing configuration keys for blob names and bucket details.

    Returns:
        dict: A dictionary where keys are data identifiers and values are the corresponding dataframes.
    """
    data_keys = ['results', 'fighters', 'events', 'rounds']
    dataframes = {
        key: load_parquet_from_gcs(
            blob_name=config['output_files']['clean'][key],
            bucket_name=config['gcs']['bucket']
        )
        for key in data_keys
    }
    return dataframes

In [4]:
def create_base_dataframe(dataframes: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """
    Creates the base dataframe by reshaping the results df to long format, 
    then joining the other datafreames.
    """
    
    df_results_clean = dataframes['results']
    df_fighters_clean = dataframes['fighters']
    df_events_clean   = dataframes['events']
    
    df_results_long = (
        df_results_clean
        
        # Reshape the results data into long format
        .pipe(wide_to_long_results)

        # Merge the other dataframes
        .merge(df_fighters_clean, on='fighter_url')
        .merge(df_events_clean, on='event_url')
        .sort_values(by=['date', 'fight_url', 'fighter_url'])
        .reset_index(drop=True)
        )
    # Create a numerical column for win (target var)
    df_results_long['is_win'] = np.where(df_results_long['result'] == 'Win', 1, 0)
    df_results_long['unique_id'] = df_results_long['fight_url'] + df_results_long['fighter_url']
    df_results_long['unique_id_opp'] = df_results_long['fight_url'] + df_results_long['opp_url']
    return df_results_long

In [5]:
def add_cumsum_columns(df: pd.DataFrame) -> pd.DataFrame:   
    """Compute the cumulative sum columns on results, bonuses, etc..."""
    df_cumsum = (
        df
        # Combine results and method type
        .assign(result_method=lambda x: x['result'].str.lower() + '_' + x['method_type'].str.lower())

        # Assign the cumulative stats (wins, kos etc...)
        .pipe(
            add_all_cumsum_columns,
            dummy_cols=['result', 'result_method', 'weight_class'],
            numerical_cols=['title_fight', 'perf_bonus', 'fight_of_the_night', 'fight_duration_seconds'],
            group_col='fighter_url',
            row_count_col='total_fights'
        )
        .drop(['result_method'], axis=1)
    )

    return df_cumsum

In [6]:
def add_timedelta_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Compute the time since previous fight and age."""
    df['date_prev'] = df.groupby('fighter_url')['date'].shift(1)
    df['time_since_prev_fight'] = (df['date'] - df['date_prev']).dt.days
    df['age'] = (df['date'] - df['date_of_birth']).dt.days/365.25
    df.drop(['date_prev'], axis=1, inplace=True)
    return df

In [7]:
def shift_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Shifts the dataframe of one to get the previous fight data"""
    df['is_win_last'] = df['is_win']
    cols_to_shift = df.columns.difference(['fight_url', 'fighter_url', 'opp_url', 'is_win', 'unique_id', 'unique_id_opp', 'date', 'result'])
    for col in cols_to_shift:
        df[f'{col}'] = df.groupby('fighter_url')[col].shift(1)
    return df

In [8]:
def add_opponent(df: pd.DataFrame) -> pd.DataFrame:
    """Adds opponent data to the dataframe, including a f1 and f2 suffix."""
    # Create a copy of the data (remember this is long format - aka 2 rows per fight)
    df_opp = df.copy().drop(['is_win'], axis=1)

    # Merge the two dataframes to get f1 and f2 data
    df_merged = (
        df
        .merge(df_opp, left_on='unique_id', right_on='unique_id_opp', suffixes=['_f1', '_f2'])
        .drop_duplicates(subset='fight_url_f1', keep='first')
        )
    return df_merged

In [9]:
def filter_dataframe(df: pd.DataFrame, result_col: str='result', date_col: str='date', date: str='2010-1-1') -> pd.DataFrame:
    """Filters the dataframe on modern date UFC and drops draws."""
    filtered_df = (
        # Drop old records + draws
        df[
            (df[date_col] >= date) &
            (df[result_col] != 'Draw')
            ]
        .reset_index(drop=True)
        )
    return filtered_df

In [10]:
DROP_COLS = ['event_url', 'method', 'round', 'time',
       'title_fight', 'perf_bonus', 'fight_of_the_night', 'time_seconds',
       'fight_duration_seconds', 'method_short', 'method_detail',
       'result_type', 'method_type', 'role',
        'full_name', 'nickname', 'height', 'reach', 'stance',
       'date_of_birth', 'record', 'event',
       'location', 'city', 'state', 'country']

In [11]:
# Training Start

In [22]:
def prep_data(dataframes: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Orchestrate all the data cleaning process."""
    df = (
        create_base_dataframe(dataframes)
        .pipe(add_cumsum_columns)
        .pipe(add_timedelta_columns)
        .pipe(shift_dataframe)
        .drop(DROP_COLS, axis=1)
        .pipe(add_opponent)
        .pipe(filter_dataframe, date_col='date_f1', result_col='result_f1')
        .select_dtypes(include=['number'])
        )
    return df

In [23]:
df = prep_data(
    load_dataframes(config)
)

In [18]:
def get_xy(df: pd.DataFrame, target_col: str) -> Tuple[pd.DataFrame, pd.Series]:
    X: pd.DataFrame = df.drop(columns=target_col)
    y: pd.Series = df[target_col]
    return X, y

In [19]:
class TrainTestSplit(NamedTuple):
    """Container for train and test split data, including features and target splits."""
    X_train: pd.DataFrame
    X_test: pd.DataFrame
    y_train: pd.Series
    y_test: pd.Series

In [20]:
def get_train_test(
        df: pd.DataFrame, 
        target_col: str,
        test_size: float = 0.2,
        random_state: int = 42
        ) -> TrainTestSplit:
    """Return a TrainTestSplit containing the train/test split of features and target from the DataFrame."""
    X, y = get_xy(df=df, target_col=target_col)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return TrainTestSplit(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)

In [21]:
X_train, X_test, y_train, y_test = get_train_test(df=df, target_col='is_win', test_size=.2, random_state=42)

NameError: name 'df' is not defined

In [ ]:
# Training End

In [ ]:
# class TrainingPipeline:
#     def __init__(self):
#         self.config = config
#         self.input_data: Dict[str, pd.DataFrame] = load_dataframes(self.config)
#         self.cleaned_data: Optional[pd.DataFrame]=None
    
#     def clean_data(self) -> pd.DataFrame:
#         self.cleaned_data = prep_data(self.input_data)
#         return self.cleaned_data

In [78]:
training_pipeline = TrainingPipeline()

In [79]:
training_pipeline.clean_data()

,height_cm_f1,reach_cm_f1,is_win,total_draw_f1,total_loss_f1,total_nc_f1,total_win_f1,total_draw_decision_f1,total_draw_other_f1,total_loss_decision_f1,...,total_womens_flyweight_f2,total_womens_strawweight_f2,total_title_fight_f2,total_perf_bonus_f2,total_fight_of_the_night_f2,total_fight_duration_seconds_f2,total_fights_f2,time_since_prev_fight_f2,age_f2,is_win_last_f2
0,172.72,180.34,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,182.88,180.34,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1047.0,4.0,364.0,31.989049,1.0
2,175.26,180.34,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,921.0,2.0,116.0,33.995893,1.0
3,193.04,195.58,1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,185.42,185.42,1,0.0,2.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,278.0,1.0,NaN,18.540726,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6716,185.42,182.88,1,0.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,4409.0,8.0,378.0,30.135524,1.0
6717,182.88,185.42,0,0.0,2.0,0.0,5.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,5759.0,9.0,56.0,33.240246,1.0
6718,172.72,180.34,0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,1905.0,3.0,119.0,29.489391,0.0
6719,160.02,160.02,0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,25.0,0.0,2.0,4.0,22365.0,26.0,98.0,39.613963,0.0
6720,187.96,187.96,1,0.0,5.0,0.0,6.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1333.0,2.0,154.0,24.648871,0.0

In [56]:
df.columns

Index(['fight_url_f1', 'weight_class_f1', 'fighter_url_f1', 'result_f1',
       'opp_url_f1', 'height_cm_f1', 'reach_cm_f1', 'date_f1', 'is_win',
       'unique_id_f1', 'unique_id_opp_f1', 'total_draw_f1', 'total_loss_f1',
       'total_nc_f1', 'total_win_f1', 'total_draw_decision_f1',
       'total_draw_other_f1', 'total_loss_decision_f1',
       'total_loss_knockout_f1', 'total_loss_other_f1',
       'total_loss_submission_f1', 'total_nc_other_f1',
       'total_win_decision_f1', 'total_win_knockout_f1', 'total_win_other_f1',
       'total_win_submission_f1', 'total_bantamweight_f1',
       'total_catch_weight_f1', 'total_featherweight_f1', 'total_flyweight_f1',
       'total_heavyweight_f1', 'total_light_heavyweight_f1',
       'total_lightweight_f1', 'total_middleweight_f1', 'total_open_weight_f1',
       'total_super_heavyweight_f1', 'total_welterweight_f1',
       'total_womens_bantamweight_f1', 'total_womens_featherweight_f1',
       'total_womens_flyweight_f1', 'total_womens_strawweight_f1',
       'total_title_fight_f1', 'total_perf_bonus_f1',
       'total_fight_of_the_night_f1', 'total_fight_duration_seconds_f1',
       'total_fights_f1', 'time_since_prev_fight_f1', 'age_f1',
       'is_win_last_f1', 'fight_url_f2', 'weight_class_f2', 'fighter_url_f2',
       'result_f2', 'opp_url_f2', 'height_cm_f2', 'reach_cm_f2', 'date_f2',
       'unique_id_f2', 'unique_id_opp_f2', 'total_draw_f2', 'total_loss_f2',
       'total_nc_f2', 'total_win_f2', 'total_draw_decision_f2',
       'total_draw_other_f2', 'total_loss_decision_f2',
       'total_loss_knockout_f2', 'total_loss_other_f2',
       'total_loss_submission_f2', 'total_nc_other_f2',
       'total_win_decision_f2', 'total_win_knockout_f2', 'total_win_other_f2',
       'total_win_submission_f2', 'total_bantamweight_f2',
       'total_catch_weight_f2', 'total_featherweight_f2', 'total_flyweight_f2',
       'total_heavyweight_f2', 'total_light_heavyweight_f2',
       'total_lightweight_f2', 'total_middleweight_f2', 'total_open_weight_f2',
       'total_super_heavyweight_f2', 'total_welterweight_f2',
       'total_womens_bantamweight_f2', 'total_womens_featherweight_f2',
       'total_womens_flyweight_f2', 'total_womens_strawweight_f2',
       'total_title_fight_f2', 'total_perf_bonus_f2',
       'total_fight_of_the_night_f2', 'total_fight_duration_seconds_f2',
       'total_fights_f2', 'time_since_prev_fight_f2', 'age_f2',
       'is_win_last_f2'],
      dtype='object')

In [49]:
df.columns

Index(['fight_url_f1', 'weight_class_f1', 'fighter_url_f1', 'opp_url_f1',
       'height_cm_f1', 'reach_cm_f1', 'date_f1', 'is_win', 'unique_id_f1',
       'unique_id_opp_f1', 'total_draw_f1', 'total_loss_f1', 'total_nc_f1',
       'total_win_f1', 'total_draw_decision_f1', 'total_draw_other_f1',
       'total_loss_decision_f1', 'total_loss_knockout_f1',
       'total_loss_other_f1', 'total_loss_submission_f1', 'total_nc_other_f1',
       'total_win_decision_f1', 'total_win_knockout_f1', 'total_win_other_f1',
       'total_win_submission_f1', 'total_bantamweight_f1',
       'total_catch_weight_f1', 'total_featherweight_f1', 'total_flyweight_f1',
       'total_heavyweight_f1', 'total_light_heavyweight_f1',
       'total_lightweight_f1', 'total_middleweight_f1', 'total_open_weight_f1',
       'total_super_heavyweight_f1', 'total_welterweight_f1',
       'total_womens_bantamweight_f1', 'total_womens_featherweight_f1',
       'total_womens_flyweight_f1', 'total_womens_strawweight_f1',
       'total_title_fight_f1', 'total_perf_bonus_f1',
       'total_fight_of_the_night_f1', 'total_fight_duration_seconds_f1',
       'total_fights_f1', 'time_since_prev_fight_f1', 'age_f1',
       'is_win_last_f1', 'fight_url_f2', 'weight_class_f2', 'fighter_url_f2',
       'opp_url_f2', 'height_cm_f2', 'reach_cm_f2', 'date_f2', 'unique_id_f2',
       'unique_id_opp_f2', 'total_draw_f2', 'total_loss_f2', 'total_nc_f2',
       'total_win_f2', 'total_draw_decision_f2', 'total_draw_other_f2',
       'total_loss_decision_f2', 'total_loss_knockout_f2',
       'total_loss_other_f2', 'total_loss_submission_f2', 'total_nc_other_f2',
       'total_win_decision_f2', 'total_win_knockout_f2', 'total_win_other_f2',
       'total_win_submission_f2', 'total_bantamweight_f2',
       'total_catch_weight_f2', 'total_featherweight_f2', 'total_flyweight_f2',
       'total_heavyweight_f2', 'total_light_heavyweight_f2',
       'total_lightweight_f2', 'total_middleweight_f2', 'total_open_weight_f2',
       'total_super_heavyweight_f2', 'total_welterweight_f2',
       'total_womens_bantamweight_f2', 'total_womens_featherweight_f2',
       'total_womens_flyweight_f2', 'total_womens_strawweight_f2',
       'total_title_fight_f2', 'total_perf_bonus_f2',
       'total_fight_of_the_night_f2', 'total_fight_duration_seconds_f2',
       'total_fights_f2', 'time_since_prev_fight_f2', 'age_f2',
       'is_win_last_f2'],
      dtype='object')

In [39]:
total_first_time_fights = len(df[(df['total_draw_f1'].isnull()) | (df['total_draw_f2'].isnull())])

In [42]:
df['is_win'].value_counts()

is_win
0    4066
1    3970
Name: count, dtype: int64

In [25]:
df.tail().to_dict(orient='records')

[{'fight_url_f1': 'http://ufcstats.com/fight-details/7b9f169016746f81',
  'weight_class_f1': 'Welterweight',
  'fighter_url_f1': 'http://ufcstats.com/fighter-details/01641ba5df0c69b0',
  'opp_url_f1': 'http://ufcstats.com/fighter-details/2558ae2e5671e318',
  'height_cm_f1': 185.42,
  'reach_cm_f1': 182.88,
  'date_f1': Timestamp('2025-02-15 00:00:00'),
  'is_win': 1,
  'unique_id_f1': 'http://ufcstats.com/fight-details/7b9f169016746f81http://ufcstats.com/fighter-details/01641ba5df0c69b0',
  'unique_id_opp_f1': 'http://ufcstats.com/fight-details/7b9f169016746f81http://ufcstats.com/fighter-details/2558ae2e5671e318',
  'total_draw_f1': 0.0,
  'total_loss_f1': 1.0,
  'total_nc_f1': 0.0,
  'total_win_f1': 3.0,
  'total_draw_decision_f1': 0.0,
  'total_draw_other_f1': 0.0,
  'total_loss_decision_f1': 0.0,
  'total_loss_knockout_f1': 1.0,
  'total_loss_other_f1': 0.0,
  'total_loss_submission_f1': 0.0,
  'total_nc_other_f1': 0.0,
  'total_win_decision_f1': 1.0,
  'total_win_knockout_f1': 0.0,
  'total_win_other_f1': 0.0,
  'total_win_submission_f1': 2.0,
  'total_bantamweight_f1': 0.0,
  'total_catch_weight_f1': 0.0,
  'total_featherweight_f1': 0.0,
  'total_flyweight_f1': 0.0,
  'total_heavyweight_f1': 0.0,
  'total_light_heavyweight_f1': 0.0,
  'total_lightweight_f1': 0.0,
  'total_middleweight_f1': 0.0,
  'total_open_weight_f1': 0.0,
  'total_super_heavyweight_f1': 0.0,
  'total_welterweight_f1': 4.0,
  'total_womens_bantamweight_f1': 0.0,
  'total_womens_featherweight_f1': 0.0,
  'total_womens_flyweight_f1': 0.0,
  'total_womens_strawweight_f1': 0.0,
  'total_title_fight_f1': 0.0,
  'total_perf_bonus_f1': 0.0,
  'total_fight_of_the_night_f1': 1.0,
  'total_fight_duration_seconds_f1': 1595.0,
  'total_fights_f1': 4.0,
  'time_since_prev_fight_f1': 252.0,
  'age_f1': 26.89664613278576,
  'is_win_last_f1': 1.0,
  'fight_url_f2': 'http://ufcstats.com/fight-details/7b9f169016746f81',
  'weight_class_f2': 'Welterweight',
  'fighter_url_f2': 'http://ufcstats.com/fighter-details/2558ae2e5671e318',
  'opp_url_f2': 'http://ufcstats.com/fighter-details/01641ba5df0c69b0',
  'height_cm_f2': 182.88,
  'reach_cm_f2': 195.58,
  'date_f2': Timestamp('2025-02-15 00:00:00'),
  'unique_id_f2': 'http://ufcstats.com/fight-details/7b9f169016746f81http://ufcstats.com/fighter-details/2558ae2e5671e318',
  'unique_id_opp_f2': 'http://ufcstats.com/fight-details/7b9f169016746f81http://ufcstats.com/fighter-details/01641ba5df0c69b0',
  'total_draw_f2': 0.0,
  'total_loss_f2': 2.0,
  'total_nc_f2': 0.0,
  'total_win_f2': 6.0,
  'total_draw_decision_f2': 0.0,
  'total_draw_other_f2': 0.0,
  'total_loss_decision_f2': 2.0,
  'total_loss_knockout_f2': 0.0,
  'total_loss_other_f2': 0.0,
  'total_loss_submission_f2': 0.0,
  'total_nc_other_f2': 0.0,
  'total_win_decision_f2': 2.0,
  'total_win_knockout_f2': 4.0,
  'total_win_other_f2': 0.0,
  'total_win_submission_f2': 0.0,
  'total_bantamweight_f2': 0.0,
  'total_catch_weight_f2': 0.0,
  'total_featherweight_f2': 0.0,
  'total_flyweight_f2': 0.0,
  'total_heavyweight_f2': 0.0,
  'total_light_heavyweight_f2': 0.0,
  'total_lightweight_f2': 0.0,
  'total_middleweight_f2': 0.0,
  'total_open_weight_f2': 0.0,
  'total_super_heavyweight_f2': 0.0,
  'total_welterweight_f2': 8.0,
  'total_womens_bantamweight_f2': 0.0,
  'total_womens_featherweight_f2': 0.0,
  'total_womens_flyweight_f2': 0.0,
  'total_womens_strawweight_f2': 0.0,
  'total_title_fight_f2': 0.0,
  'total_perf_bonus_f2': 4.0,
  'total_fight_of_the_night_f2': 0.0,
  'total_fight_duration_seconds_f2': 4409.0,
  'total_fights_f2': 8.0,
  'time_since_prev_fight_f2': 378.0,
  'age_f2': 30.135523613963038,
  'is_win_last_f2': 1.0},
 {'fight_url_f1': 'http://ufcstats.com/fight-details/875b249ebe45a66b',
  'weight_class_f1': 'Middleweight',
  'fighter_url_f1': 'http://ufcstats.com/fighter-details/260e9e0d4954aea6',
  'opp_url_f1': 'http://ufcstats.com/fighter-details/5f61780fe5e9b6d0',
  'height_cm_f1': 182.88,
  'reach_cm_f1': 185.42000000000002,
  'date_f1': Timestamp('2025-02-15 00:00:00'),
  'is_win': 0,
  'unique_id_f1': 'http://ufcstats.com/fight-details/875b249ebe45a66bhttp://ufcstats.com/fighter-details/260e9e0d4954aea6',
  'unique_id_opp_f1': 'http://ufcstats.com/fight-details/875b249ebe45a66bhttp://ufcstats.com/fighter-details/5f61780fe5e9b6d0',
  'total_draw_f1': 0.0,
  'total_loss_f1': 2.0,
  'total_nc_f1': 0.0,
  'total_win_f1': 5.0,
  'total_draw_decision_f1': 0.0,
  'total_draw_other_f1': 0.0,
  'total_loss_decision_f1': 1.0,
  'total_loss_knockout_f1': 0.0,
  'total_loss_other_f1': 0.0,
  'total_loss_submission_f1': 1.0,
  'total_nc_other_f1': 0.0,
  'total_win_decision_f1': 0.0,
  'total_win_knockout_f1': 0.0,
  'total_win_other_f1': 0.0,
  'total_win_submission_f1': 5.0,
  'total_bantamweight_f1': 0.0,
  'total_catch_weight_f1': 0.0,
  'total_featherweight_f1': 0.0,
  'total_flyweight_f1': 0.0,
  'total_heavyweight_f1': 0.0,
  'total_light_heavyweight_f1': 0.0,
  'total_lightweight_f1': 0.0,
  'total_middleweight_f1': 7.0,
  'total_open_weight_f1': 0.0,
  'total_super_heavyweight_f1': 0.0,
  'total_welterweight_f1': 0.0,
  'total_womens_bantamweight_f1': 0.0,
  'total_womens_featherweight_f1': 0.0,
  'total_womens_flyweight_f1': 0.0,
  'total_womens_strawweight_f1': 0.0,
  'total_title_fight_f1': 0.0,
  'total_perf_bonus_f1': 4.0,
  'total_fight_of_the_night_f1': 0.0,
  'total_fight_duration_seconds_f1': 3447.0,
  'total_fights_f1': 7.0,
  'time_since_prev_fight_f1': 287.0,
  'age_f1': 34.37645448323067,
  'is_win_last_f1': 1.0,
  'fight_url_f2': 'http://ufcstats.com/fight-details/875b249ebe45a66b',
  'weight_class_f2': 'Middleweight',
  'fighter_url_f2': 'http://ufcstats.com/fighter-details/5f61780fe5e9b6d0',
  'opp_url_f2': 'http://ufcstats.com/fighter-details/260e9e0d4954aea6',
  'height_cm_f2': 182.88,
  'reach_cm_f2': 185.42000000000002,
  'date_f2': Timestamp('2025-02-15 00:00:00'),
  'unique_id_f2': 'http://ufcstats.com/fight-details/875b249ebe45a66bhttp://ufcstats.com/fighter-details/5f61780fe5e9b6d0',
  'unique_id_opp_f2': 'http://ufcstats.com/fight-details/875b249ebe45a66bhttp://ufcstats.com/fighter-details/260e9e0d4954aea6',
  'total_draw_f2': 0.0,
  'total_loss_f2': 2.0,
  'total_nc_f2': 0.0,
  'total_win_f2': 7.0,
  'total_draw_decision_f2': 0.0,
  'total_draw_other_f2': 0.0,
  'total_loss_decision_f2': 0.0,
  'total_loss_knockout_f2': 2.0,
  'total_loss_other_f2': 0.0,
  'total_loss_submission_f2': 0.0,
  'total_nc_other_f2': 0.0,
  'total_win_decision_f2': 4.0,
  'total_win_knockout_f2': 1.0,
  'total_win_other_f2': 0.0,
  'total_win_submission_f2': 2.0,
  'total_bantamweight_f2': 0.0,
  'total_catch_weight_f2': 0.0,
  'total_featherweight_f2': 0.0,
  'total_flyweight_f2': 0.0,
  'total_heavyweight_f2': 0.0,
  'total_light_heavyweight_f2': 0.0,
  'total_lightweight_f2': 0.0,
  'total_middleweight_f2': 9.0,
  'total_open_weight_f2': 0.0,
  'total_super_heavyweight_f2': 0.0,
  'total_welterweight_f2': 0.0,
  'total_womens_bantamweight_f2': 0.0,
  'total_womens_featherweight_f2': 0.0,
  'total_womens_flyweight_f2': 0.0,
  'total_womens_strawweight_f2': 0.0,
  'total_title_fight_f2': 0.0,
  'total_perf_bonus_f2': 1.0,
  'total_fight_of_the_night_f2': 0.0,
  'total_fight_duration_seconds_f2': 5759.0,
  'total_fights_f2': 9.0,
  'time_since_prev_fight_f2': 56.0,
  'age_f2': 33.24024640657084,
  'is_win_last_f2': 1.0},
 {'fight_url_f1': 'http://ufcstats.com/fight-details/ce1436a9b58902a7',
  'weight_class_f1': 'Lightweight',
  'fighter_url_f1': 'http://ufcstats.com/fighter-details/eb393afdbe3293d5',
  'opp_url_f1': 'http://ufcstats.com/fighter-details/ff62013d2fce6d13',
  'height_cm_f1': 172.72,
  'reach_cm_f1': 180.34,
  'date_f1': Timestamp('2025-02-15 00:00:00'),
  'is_win': 0,
  'unique_id_f1': 'http://ufcstats.com/fight-details/ce1436a9b58902a7http://ufcstats.com/fighter-details/eb393afdbe3293d5',
  'unique_id_opp_f1': 'http://ufcstats.com/fight-details/ce1436a9b58902a7http://ufcstats.com/fighter-details/ff62013d2fce6d13',
  'total_draw_f1': 0.0,
  'total_loss_f1': 1.0,
  'total_nc_f1': 0.0,
  'total_win_f1': 2.0,
  'total_draw_decision_f1': 0.0,
  'total_draw_other_f1': 0.0,
  'total_loss_decision_f1': 0.0,
  'total_loss_knockout_f1': 0.0,
  'total_loss_other_f1': 0.0,
  'total_loss_submission_f1': 1.0,
  'total_nc_other_f1': 0.0,
  'total_win_decision_f1': 1.0,
  'total_win_knockout_f1': 1.0,
  'total_win_other_f1': 0.0,
  'total_win_submission_f1': 0.0,
  'total_bantamweight_f1': 0.0,
  'total_catch_weight_f1': 0.0,
  'total_featherweight_f1': 0.0,
  'total_flyweight_f1': 0.0,
  'total_heavyweight_f1': 0.0,
  'total_light_heavyweight_f1': 0.0,
  'total_lightweight_f1': 3.0,
  'total_middleweight_f1': 0.0,
  'total_open_weight_f1': 0.0,
  'total_super_heavyweight_f1': 0.0,
  'total_welterweight_f1': 0.0,
  'total_womens_bantamweight_f1': 0.0,
  'total_womens_featherweight_f1': 0.0,
  'total_womens_flyweight_f1': 0.0,
  'total_womens_strawweight_f1': 0.0,
  'total_title_fight_f1': 0.0,
  'total_perf_bonus_f1': 1.0,
  'total_fight_of_the_night_f1': 0.0,
  'total_fight_duration_seconds_f1': 1625.0,
  'total_fights_f1': 3.0,
  'time_since_prev_fight_f1': 308.0,
  'age_f1': 28.35044490075291,
  'is_win_last_f1': 1.0,
  'fight_url_f2': 'http://ufcstats.com/fight-details/ce1436a9b58902a7',
  'weight_class_f2': 'Lightweight',
  'fighter_url_f2': 'http://ufcstats.com/fighter-details/ff62013d2fce6d13',
  'opp_url_f2': 'http://ufcstats.com/fighter-details/eb393afdbe3293d5',
  'height_cm_f2': 177.8,
  'reach_cm_f2': 175.26,
  'date_f2': Timestamp('2025-02-15 00:00:00'),
  'unique_id_f2': 'http://ufcstats.com/fight-details/ce1436a9b58902a7http://ufcstats.com/fighter-details/ff62013d2fce6d13',
  'unique_id_opp_f2': 'http://ufcstats.com/fight-details/ce1436a9b58902a7http://ufcstats.com/fighter-details/eb393afdbe3293d5',
  'total_draw_f2': 1.0,
  'total_loss_f2': 0.0,
  'total_nc_f2': 0.0,
  'total_win_f2': 2.0,
  'total_draw_decision_f2': 1.0,
  'total_draw_other_f2': 0.0,
  'total_loss_decision_f2': 0.0,
  'total_loss_knockout_f2': 0.0,
  'total_loss_other_f2': 0.0,
  'total_loss_submission_f2': 0.0,
  'total_nc_other_f2': 0.0,
  'total_win_decision_f2': 0.0,
  'total_win_knockout_f2': 1.0,
  'total_win_other_f2': 0.0,
  'total_win_submission_f2': 1.0,
  'total_bantamweight_f2': 0.0,
  'total_catch_weight_f2': 0.0,
  'total_featherweight_f2': 0.0,
  'total_flyweight_f2': 0.0,
  'total_heavyweight_f2': 0.0,
  'total_light_heavyweight_f2': 0.0,
  'total_lightweight_f2': 3.0,
  'total_middleweight_f2': 0.0,
  'total_open_weight_f2': 0.0,
  'total_super_heavyweight_f2': 0.0,
  'total_welterweight_f2': 0.0,
  'total_womens_bantamweight_f2': 0.0,
  'total_womens_featherweight_f2': 0.0,
  'total_womens_flyweight_f2': 0.0,
  'total_womens_strawweight_f2': 0.0,
  'total_title_fight_f2': 0.0,
  'total_perf_bonus_f2': 0.0,
  'total_fight_of_the_night_f2': 2.0,
  'total_fight_duration_seconds_f2': 1905.0,
  'total_fights_f2': 3.0,
  'time_since_prev_fight_f2': 119.0,
  'age_f2': 29.489390828199863,
  'is_win_last_f2': 0.0},
 {'fight_url_f1': 'http://ufcstats.com/fight-details/f4817d5cbe9be532',
  'weight_class_f1': "Women's Strawweight",
  'fighter_url_f1': 'http://ufcstats.com/fighter-details/8bd4200561c77a62',
  'opp_url_f1': 'http://ufcstats.com/fighter-details/f0feeb2192937424',
  'height_cm_f1': 160.02,
  'reach_cm_f1': 160.02,
  'date_f1': Timestamp('2025-02-15 00:00:00'),
  'is_win': 0,
  'unique_id_f1': 'http://ufcstats.com/fight-details/f4817d5cbe9be532http://ufcstats.com/fighter-details/8bd4200561c77a62',
  'unique_id_opp_f1': 'http://ufcstats.com/fight-details/f4817d5cbe9be532http://ufcstats.com/fighter-details/f0feeb2192937424',
  'total_draw_f1': 0.0,
  'total_loss_f1': 1.0,
  'total_nc_f1': 0.0,
  'total_win_f1': 2.0,
  'total_draw_decision_f1': 0.0,
  'total_draw_other_f1': 0.0,
  'total_loss_decision_f1': 0.0,
  'total_loss_knockout_f1': 0.0,
  'total_loss_other_f1': 0.0,
  'total_loss_submission_f1': 1.0,
  'total_nc_other_f1': 0.0,
  'total_win_decision_f1': 1.0,
  'total_win_knockout_f1': 0.0,
  'total_win_other_f1': 0.0,
  'total_win_submission_f1': 1.0,
  'total_bantamweight_f1': 0.0,
  'total_catch_weight_f1': 0.0,
  'total_featherweight_f1': 0.0,
  'total_flyweight_f1': 0.0,
  'total_heavyweight_f1': 0.0,
  'total_light_heavyweight_f1': 0.0,
  'total_lightweight_f1': 0.0,
  'total_middleweight_f1': 0.0,
  'total_open_weight_f1': 0.0,
  'total_super_heavyweight_f1': 0.0,
  'total_welterweight_f1': 0.0,
  'total_womens_bantamweight_f1': 0.0,
  'total_womens_featherweight_f1': 0.0,
  'total_womens_flyweight_f1': 1.0,
  'total_womens_strawweight_f1': 2.0,
  'total_title_fight_f1': 0.0,
  'total_perf_bonus_f1': 1.0,
  'total_fight_of_the_night_f1': 0.0,
  'total_fight_duration_seconds_f1': 1187.0,
  'total_fights_f1': 3.0,
  'time_since_prev_fight_f1': 140.0,
  'age_f1': 30.075290896646134,
  'is_win_last_f1': 1.0,
  'fight_url_f2': 'http://ufcstats.com/fight-details/f4817d5cbe9be532',
  'weight_class_f2': "Women's Strawweight",
  'fighter_url_f2': 'http://ufcstats.com/fighter-details/f0feeb2192937424',
  'opp_url_f2': 'http://ufcstats.com/fighter-details/8bd4200561c77a62',
  'height_cm_f2': 160.02,
  'reach_cm_f2': 162.56,
  'date_f2': Timestamp('2025-02-15 00:00:00'),
  'unique_id_f2': 'http://ufcstats.com/fight-details/f4817d5cbe9be532http://ufcstats.com/fighter-details/f0feeb2192937424',
  'unique_id_opp_f2': 'http://ufcstats.com/fight-details/f4817d5cbe9be532http://ufcstats.com/fighter-details/8bd4200561c77a62',
  'total_draw_f2': 0.0,
  'total_loss_f2': 14.0,
  'total_nc_f2': 0.0,
  'total_win_f2': 12.0,
  'total_draw_decision_f2': 0.0,
  'total_draw_other_f2': 0.0,
  'total_loss_decision_f2': 12.0,
  'total_loss_knockout_f2': 0.0,
  'total_loss_other_f2': 0.0,
  'total_loss_submission_f2': 2.0,
  'total_nc_other_f2': 0.0,
  'total_win_decision_f2': 9.0,
  'total_win_knockout_f2': 2.0,
  'total_win_other_f2': 0.0,
  'total_win_submission_f2': 1.0,
  'total_bantamweight_f2': 0.0,
  'total_catch_weight_f2': 1.0,
  'total_featherweight_f2': 0.0,
  'total_flyweight_f2': 0.0,
  'total_heavyweight_f2': 0.0,
  'total_light_heavyweight_f2': 0.0,
  'total_lightweight_f2': 0.0,
  'total_middleweight_f2': 0.0,
  'total_open_weight_f2': 0.0,
  'total_super_heavyweight_f2': 0.0,
  'total_welterweight_f2': 0.0,
  'total_womens_bantamweight_f2': 0.0,
  'total_womens_featherweight_f2': 0.0,
  'total_womens_flyweight_f2': 0.0,
  'total_womens_strawweight_f2': 25.0,
  'total_title_fight_f2': 0.0,
  'total_perf_bonus_f2': 2.0,
  'total_fight_of_the_night_f2': 4.0,
  'total_fight_duration_seconds_f2': 22365.0,
  'total_fights_f2': 26.0,
  'time_since_prev_fight_f2': 98.0,
  'age_f2': 39.61396303901437,
  'is_win_last_f2': 0.0},
 {'fight_url_f1': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4',
  'weight_class_f1': 'Middleweight',
  'fighter_url_f1': 'http://ufcstats.com/fighter-details/4144798612ef96e5',
  'opp_url_f1': 'http://ufcstats.com/fighter-details/a817e238b2747404',
  'height_cm_f1': 187.96,
  'reach_cm_f1': 187.96,
  'date_f1': Timestamp('2025-02-15 00:00:00'),
  'is_win': 1,
  'unique_id_f1': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4http://ufcstats.com/fighter-details/4144798612ef96e5',
  'unique_id_opp_f1': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4http://ufcstats.com/fighter-details/a817e238b2747404',
  'total_draw_f1': 0.0,
  'total_loss_f1': 5.0,
  'total_nc_f1': 0.0,
  'total_win_f1': 6.0,
  'total_draw_decision_f1': 0.0,
  'total_draw_other_f1': 0.0,
  'total_loss_decision_f1': 1.0,
  'total_loss_knockout_f1': 3.0,
  'total_loss_other_f1': 0.0,
  'total_loss_submission_f1': 1.0,
  'total_nc_other_f1': 0.0,
  'total_win_decision_f1': 1.0,
  'total_win_knockout_f1': 4.0,
  'total_win_other_f1': 0.0,
  'total_win_submission_f1': 1.0,
  'total_bantamweight_f1': 0.0,
  'total_catch_weight_f1': 0.0,
  'total_featherweight_f1': 0.0,
  'total_flyweight_f1': 0.0,
  'total_heavyweight_f1': 0.0,
  'total_light_heavyweight_f1': 0.0,
  'total_lightweight_f1': 0.0,
  'total_middleweight_f1': 11.0,
  'total_open_weight_f1': 0.0,
  'total_super_heavyweight_f1': 0.0,
  'total_welterweight_f1': 0.0,
  'total_womens_bantamweight_f1': 0.0,
  'total_womens_featherweight_f1': 0.0,
  'total_womens_flyweight_f1': 0.0,
  'total_womens_strawweight_f1': 0.0,
  'total_title_fight_f1': 0.0,
  'total_perf_bonus_f1': 2.0,
  'total_fight_of_the_night_f1': 0.0,
  'total_fight_duration_seconds_f1': 5342.0,
  'total_fights_f1': 11.0,
  'time_since_prev_fight_f1': 154.0,
  'age_f1': 26.759753593429156,
  'is_win_last_f1': 0.0,
  'fight_url_f2': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4',
  'weight_class_f2': 'Middleweight',
  'fighter_url_f2': 'http://ufcstats.com/fighter-details/a817e238b2747404',
  'opp_url_f2': 'http://ufcstats.com/fighter-details/4144798612ef96e5',
  'height_cm_f2': 182.88,
  'reach_cm_f2': 190.5,
  'date_f2': Timestamp('2025-02-15 00:00:00'),
  'unique_id_f2': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4http://ufcstats.com/fighter-details/a817e238b2747404',
  'unique_id_opp_f2': 'http://ufcstats.com/fight-details/f5386c98fea7f5d4http://ufcstats.com/fighter-details/4144798612ef96e5',
  'total_draw_f2': 0.0,
  'total_loss_f2': 2.0,
  'total_nc_f2': 0.0,
  'total_win_f2': 0.0,
  'total_draw_decision_f2': 0.0,
  'total_draw_other_f2': 0.0,
  'total_loss_decision_f2': 1.0,
  'total_loss_knockout_f2': 1.0,
  'total_loss_other_f2': 0.0,
  'total_loss_submission_f2': 0.0,
  'total_nc_other_f2': 0.0,
  'total_win_decision_f2': 0.0,
  'total_win_knockout_f2': 0.0,
  'total_win_other_f2': 0.0,
  'total_win_submission_f2': 0.0,
  'total_bantamweight_f2': 0.0,
  'total_catch_weight_f2': 0.0,
  'total_featherweight_f2': 0.0,
  'total_flyweight_f2': 0.0,
  'total_heavyweight_f2': 0.0,
  'total_light_heavyweight_f2': 0.0,
  'total_lightweight_f2': 0.0,
  'total_middleweight_f2': 2.0,
  'total_open_weight_f2': 0.0,
  'total_super_heavyweight_f2': 0.0,
  'total_welterweight_f2': 0.0,
  'total_womens_bantamweight_f2': 0.0,
  'total_womens_featherweight_f2': 0.0,
  'total_womens_flyweight_f2': 0.0,
  'total_womens_strawweight_f2': 0.0,
  'total_title_fight_f2': 0.0,
  'total_perf_bonus_f2': 1.0,
  'total_fight_of_the_night_f2': 0.0,
  'total_fight_duration_seconds_f2': 1333.0,
  'total_fights_f2': 2.0,
  'time_since_prev_fight_f2': 154.0,
  'age_f2': 24.648870636550306,
  'is_win_last_f2': 0.0}]

In [270]:
add_opponent(df)

,fight_url_f1,weight_class_f1,fighter_url_f1,opp_url_f1,height_cm_f1,reach_cm_f1,date_f1,is_win,unique_id_f1,unique_id_opp_f1,...,total_womens_flyweight_f2,total_womens_strawweight_f2,total_title_fight_f2,total_perf_bonus_f2,total_fight_of_the_night_f2,total_fight_duration_seconds_f2,total_fights_f2,time_since_prev_fight_f2,age_f2,is_win_last_f2
0,http://ufcstats.com/fight-details/00835554f95f...,NaN,http://ufcstats.com/fighter-details/429e7d3725...,http://ufcstats.com/fighter-details/46c8ec317a...,NaN,NaN,1994-03-11,1,http://ufcstats.com/fight-details/00835554f95f...,http://ufcstats.com/fight-details/00835554f95f...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://ufcstats.com/fight-details/17ee4caf0698...,NaN,http://ufcstats.com/fighter-details/6e02c31876...,http://ufcstats.com/fighter-details/749685d24e...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/17ee4caf0698...,http://ufcstats.com/fight-details/17ee4caf0698...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://ufcstats.com/fight-details/3b020d4914b4...,NaN,http://ufcstats.com/fighter-details/96087e90d9...,http://ufcstats.com/fighter-details/a6c2f5381d...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/3b020d4914b4...,http://ufcstats.com/fight-details/3b020d4914b4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,http://ufcstats.com/fight-details/4acab67848e7...,NaN,http://ufcstats.com/fighter-details/a683f9ddb7...,http://ufcstats.com/fighter-details/be9d259be0...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/4acab67848e7...,http://ufcstats.com/fight-details/4acab67848e7...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,http://ufcstats.com/fight-details/4b9ae533ccb3...,Open Weight,http://ufcstats.com/fighter-details/46c8ec317a...,http://ufcstats.com/fighter-details/ea0ad15545...,187.96,NaN,1994-03-11,1,http://ufcstats.com/fight-details/4b9ae533ccb3...,http://ufcstats.com/fight-details/4b9ae533ccb3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16062,http://ufcstats.com/fight-details/7b9f16901674...,Welterweight,http://ufcstats.com/fighter-details/01641ba5df...,http://ufcstats.com/fighter-details/2558ae2e56...,185.42,182.88,2025-02-15,1,http://ufcstats.com/fight-details/7b9f16901674...,http://ufcstats.com/fight-details/7b9f16901674...,...,0.0,0.0,0.0,4.0,0.0,4409.0,8.0,378.0,30.135524,1.0
16064,http://ufcstats.com/fight-details/875b249ebe45...,Middleweight,http://ufcstats.com/fighter-details/260e9e0d49...,http://ufcstats.com/fighter-details/5f61780fe5...,182.88,185.42,2025-02-15,0,http://ufcstats.com/fight-details/875b249ebe45...,http://ufcstats.com/fight-details/875b249ebe45...,...,0.0,0.0,0.0,1.0,0.0,5759.0,9.0,56.0,33.240246,1.0
16066,http://ufcstats.com/fight-details/ce1436a9b589...,Lightweight,http://ufcstats.com/fighter-details/eb393afdbe...,http://ufcstats.com/fighter-details/ff62013d2f...,172.72,180.34,2025-02-15,0,http://ufcstats.com/fight-details/ce1436a9b589...,http://ufcstats.com/fight-details/ce1436a9b589...,...,0.0,0.0,0.0,0.0,2.0,1905.0,3.0,119.0,29.489391,0.0
16068,http://ufcstats.com/fight-details/f4817d5cbe9b...,Women's Strawweight,http://ufcstats.com/fighter-details/8bd4200561...,http://ufcstats.com/fighter-details/f0feeb2192...,160.02,160.02,2025-02-15,0,http://ufcstats.com/fight-details/f4817d5cbe9b...,http://ufcstats.com/fight-details/f4817d5cbe9b...,...,0.0,25.0,0.0,2.0,4.0,22365.0,26.0,98.0,39.613963,0.0
16070,http://ufcstats.com/fight-details/f5386c98fea7...,Middleweight,http://ufcstats.com/fighter-details/4144798612...,http://ufcstats.com/fighter-details/a817e238b2...,187.96,187.96,2025-02-15,1,http://ufcstats.com/fight-details/f5386c98fea7...,http://ufcstats.com/fight-details/f5386c98fea7...,...,0.0,0.0,0.0,1.0,0.0,1333.0,2.0,154.0,24.648871,0.0

In [256]:
df_opp = df.copy().drop(['is_win'], axis=1)

In [258]:
df_merged = df.merge(df_opp, left_on='unique_id', right_on='unique_id_opp', suffixes=['_f1', '_f2'])

In [268]:
df_merged.drop_duplicates(subset='fight_url_f1', keep='first')

,fight_url_f1,weight_class_f1,fighter_url_f1,opp_url_f1,height_cm_f1,reach_cm_f1,date_f1,is_win,unique_id_f1,unique_id_opp_f1,...,total_womens_flyweight_f2,total_womens_strawweight_f2,total_title_fight_f2,total_perf_bonus_f2,total_fight_of_the_night_f2,total_fight_duration_seconds_f2,total_fights_f2,time_since_prev_fight_f2,age_f2,is_win_last_f2
0,http://ufcstats.com/fight-details/00835554f95f...,NaN,http://ufcstats.com/fighter-details/429e7d3725...,http://ufcstats.com/fighter-details/46c8ec317a...,NaN,NaN,1994-03-11,1,http://ufcstats.com/fight-details/00835554f95f...,http://ufcstats.com/fight-details/00835554f95f...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://ufcstats.com/fight-details/17ee4caf0698...,NaN,http://ufcstats.com/fighter-details/6e02c31876...,http://ufcstats.com/fighter-details/749685d24e...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/17ee4caf0698...,http://ufcstats.com/fight-details/17ee4caf0698...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://ufcstats.com/fight-details/3b020d4914b4...,NaN,http://ufcstats.com/fighter-details/96087e90d9...,http://ufcstats.com/fighter-details/a6c2f5381d...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/3b020d4914b4...,http://ufcstats.com/fight-details/3b020d4914b4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,http://ufcstats.com/fight-details/4acab67848e7...,NaN,http://ufcstats.com/fighter-details/a683f9ddb7...,http://ufcstats.com/fighter-details/be9d259be0...,NaN,NaN,1994-03-11,0,http://ufcstats.com/fight-details/4acab67848e7...,http://ufcstats.com/fight-details/4acab67848e7...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,http://ufcstats.com/fight-details/4b9ae533ccb3...,Open Weight,http://ufcstats.com/fighter-details/46c8ec317a...,http://ufcstats.com/fighter-details/ea0ad15545...,187.96,NaN,1994-03-11,1,http://ufcstats.com/fight-details/4b9ae533ccb3...,http://ufcstats.com/fight-details/4b9ae533ccb3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16062,http://ufcstats.com/fight-details/7b9f16901674...,Welterweight,http://ufcstats.com/fighter-details/01641ba5df...,http://ufcstats.com/fighter-details/2558ae2e56...,185.42,182.88,2025-02-15,1,http://ufcstats.com/fight-details/7b9f16901674...,http://ufcstats.com/fight-details/7b9f16901674...,...,0.0,0.0,0.0,4.0,0.0,4409.0,8.0,378.0,30.135524,1.0
16064,http://ufcstats.com/fight-details/875b249ebe45...,Middleweight,http://ufcstats.com/fighter-details/260e9e0d49...,http://ufcstats.com/fighter-details/5f61780fe5...,182.88,185.42,2025-02-15,0,http://ufcstats.com/fight-details/875b249ebe45...,http://ufcstats.com/fight-details/875b249ebe45...,...,0.0,0.0,0.0,1.0,0.0,5759.0,9.0,56.0,33.240246,1.0
16066,http://ufcstats.com/fight-details/ce1436a9b589...,Lightweight,http://ufcstats.com/fighter-details/eb393afdbe...,http://ufcstats.com/fighter-details/ff62013d2f...,172.72,180.34,2025-02-15,0,http://ufcstats.com/fight-details/ce1436a9b589...,http://ufcstats.com/fight-details/ce1436a9b589...,...,0.0,0.0,0.0,0.0,2.0,1905.0,3.0,119.0,29.489391,0.0
16068,http://ufcstats.com/fight-details/f4817d5cbe9b...,Women's Strawweight,http://ufcstats.com/fighter-details/8bd4200561...,http://ufcstats.com/fighter-details/f0feeb2192...,160.02,160.02,2025-02-15,0,http://ufcstats.com/fight-details/f4817d5cbe9b...,http://ufcstats.com/fight-details/f4817d5cbe9b...,...,0.0,25.0,0.0,2.0,4.0,22365.0,26.0,98.0,39.613963,0.0
16070,http://ufcstats.com/fight-details/f5386c98fea7...,Middleweight,http://ufcstats.com/fighter-details/4144798612...,http://ufcstats.com/fighter-details/a817e238b2...,187.96,187.96,2025-02-15,1,http://ufcstats.com/fight-details/f5386c98fea7...,http://ufcstats.com/fight-details/f5386c98fea7...,...,0.0,0.0,0.0,1.0,0.0,1333.0,2.0,154.0,24.648871,0.0

In [185]:
df_merged['opp_url_f1'] == df_merged['fighter_url_f2']

0        True
1        True
2        True
3        True
4        True
         ...
10067    True
10068    True
10069    True
10070    True
10071    True
Length: 10072, dtype: bool

In [153]:
df

,fight_url,fighter_url,height_cm,reach_cm,date,is_win,result_method,total_draw,total_loss,total_nc,...,total_welterweight_prev,total_win_prev,total_win_decision_prev,total_win_knockout_prev,total_win_other_prev,total_win_submission_prev,total_womens_bantamweight_prev,total_womens_featherweight_prev,total_womens_flyweight_prev,total_womens_strawweight_prev
0,http://ufcstats.com/fight-details/0949caefc673...,http://ufcstats.com/fighter-details/15b1b21cd7...,172.72,180.34,2010-01-02,1,win_decision,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://ufcstats.com/fight-details/0949caefc673...,http://ufcstats.com/fighter-details/a0c139b34f...,175.26,175.26,2010-01-02,0,loss_decision,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://ufcstats.com/fight-details/0e05f54d8b66...,http://ufcstats.com/fighter-details/179f1948dc...,182.88,180.34,2010-01-02,1,win_knockout,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,http://ufcstats.com/fight-details/0e05f54d8b66...,http://ufcstats.com/fighter-details/aae99701b2...,185.42,193.04,2010-01-02,0,loss_knockout,0,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://ufcstats.com/fight-details/24e14c482414...,http://ufcstats.com/fighter-details/d81ac73941...,175.26,180.34,2010-01-02,1,win_knockout,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,http://ufcstats.com/fight-details/ce1436a9b589...,http://ufcstats.com/fighter-details/ff62013d2f...,177.80,175.26,2025-02-15,1,win_knockout,1,0,0,...,0.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
13438,http://ufcstats.com/fight-details/f4817d5cbe9b...,http://ufcstats.com/fighter-details/8bd4200561...,160.02,160.02,2025-02-15,0,loss_decision,0,2,0,...,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
13439,http://ufcstats.com/fight-details/f4817d5cbe9b...,http://ufcstats.com/fighter-details/f0feeb2192...,160.02,162.56,2025-02-15,1,win_decision,0,14,0,...,0.0,12.0,9.0,2.0,0.0,1.0,0.0,0.0,0.0,25.0
13440,http://ufcstats.com/fight-details/f5386c98fea7...,http://ufcstats.com/fighter-details/4144798612...,187.96,187.96,2025-02-15,1,win_knockout,0,5,0,...,0.0,6.0,1.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
13441,http://ufcstats.com/fight-details/f5386c98fea7...,http://ufcstats.com/fighter-details/a817e238b2...,182.88,190.50,2025-02-15,0,loss_knockout,0,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,fight_url,fighter_url,height_cm,reach_cm,date,is_win,result_method,total_draw,total_loss,total_nc,...,total_womens_featherweight,total_womens_flyweight,total_womens_strawweight,total_title_fight,total_perf_bonus,total_fight_of_the_night,total_fight_duration_seconds,total_fights,time_since_prev_fight,age
0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,http://ufcstats.com/fight-details/e4620f3fa451...,http://ufcstats.com/fighter-details/ff62013d2f...,177.80,175.26,2023-07-15,1.0,win_submission,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1005.0,2.0,147.0,29.163587
13438,http://ufcstats.com/fight-details/c60a317c7767...,http://ufcstats.com/fighter-details/8bd4200561...,160.02,160.02,2024-09-14,1.0,win_submission,0.0,1.0,0.0,...,0.0,1.0,2.0,0.0,1.0,0.0,1187.0,3.0,140.0,30.075291
13439,http://ufcstats.com/fight-details/70afe9e0d242...,http://ufcstats.com/fighter-details/f0feeb2192...,160.02,162.56,2024-08-24,0.0,loss_decision,0.0,14.0,0.0,...,0.0,0.0,25.0,0.0,2.0,4.0,22365.0,26.0,98.0,39.613963
13440,http://ufcstats.com/fight-details/2cbd53e43d3f...,http://ufcstats.com/fighter-details/4144798612...,187.96,187.96,2024-08-24,0.0,loss_submission,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,5342.0,11.0,154.0,26.759754
13441,http://ufcstats.com/fight-details/f734b497add7...,http://ufcstats.com/fighter-details/a817e238b2...,182.88,190.50,2024-09-07,0.0,loss_decision,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1333.0,2.0,154.0,24.648871

In [265]:
df_merged[df_merged['fighter_url_f1'] == 'http://ufcstats.com/fighter-details/ff62013d2fce6d13'][['is_win', 'is_win_last_f1']]

       is_win  is_win_last_f1
13991       1             NaN
14457       1             1.0
14805       0             1.0
16067       1             0.0

In [90]:
df.tail()['fighter_url'].values

array(['http://ufcstats.com/fighter-details/ff62013d2fce6d13',
       'http://ufcstats.com/fighter-details/8bd4200561c77a62',
       'http://ufcstats.com/fighter-details/f0feeb2192937424',
       'http://ufcstats.com/fighter-details/4144798612ef96e5',
       'http://ufcstats.com/fighter-details/a817e238b2747404'],
      dtype=object)

In [82]:
df.columns

Index(['fight_url', 'event_url', 'weight_class', 'method', 'round', 'time',
       'title_fight', 'perf_bonus', 'fight_of_the_night', 'time_seconds',
       'fight_duration_seconds', 'method_short', 'method_detail',
       'result_type', 'method_type', 'fighter_url', 'result', 'role',
       'opp_url', 'full_name', 'nickname', 'height', 'reach', 'stance',
       'date_of_birth', 'record', 'height_cm', 'reach_cm', 'event', 'date',
       'location', 'city', 'state', 'country', 'is_win', 'result_method',
       'total_draw', 'total_loss', 'total_nc', 'total_win',
       'total_draw_decision', 'total_draw_other', 'total_loss_decision',
       'total_loss_knockout', 'total_loss_other', 'total_loss_submission',
       'total_nc_other', 'total_win_decision', 'total_win_knockout',
       'total_win_other', 'total_win_submission', 'total_bantamweight',
       'total_catch_weight', 'total_featherweight', 'total_flyweight',
       'total_heavyweight', 'total_light_heavyweight', 'total_lightweight',
       'total_middleweight', 'total_open_weight', 'total_super_heavyweight',
       'total_welterweight', 'total_womens_bantamweight',
       'total_womens_featherweight', 'total_womens_flyweight',
       'total_womens_strawweight', 'total_title_fight', 'total_perf_bonus',
       'total_fight_of_the_night', 'total_fight_duration_seconds',
       'total_fights'],
      dtype='object')

In [ ]:
# Drop old records + draws
# Join on fight + fighter = opponent
# Drop duplicated fights
# Validate balance of target